version: '2'
services:
  app:
    image: pocbuildersregistry.azurecr.io/builders-app:v2
    build:
      context: .
    container_name: builders-app
    depends_on:
      - cadastro-postgresql
    ports:
    - 8080:8080
  cadastro-postgresql:
    extends:
      file: src/main/docker/postgres.yml
      service: cadastro-postgresql
